spring:
  datasource:
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: mysqluser
    password: mysqlpassword
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.xml
    check-change-log-location: true
    drop-first: true
logging:
  level:
    ROOT: ERROR
    org:
      springframework: ERROR
      hibernate: ERROR
    com:
      petrego: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"